using System;
using System.Collections.Generic;
using System.Text;

namespace bilsoft_mobil_app.Pages.Ajanda
{
    public class UserVeriler
    {
        public int id { get; set; }
        public string kullanici { get; set; }
        public string sifre { get; set; }
        public string cariKart { get; set; }
        public string stok { get; set; }
        public string taksit { get; set; }
        public string satis { get; set; }
        public string fatura { get; set; }
        public string kasa { get; set; }
        public string banka { get; set; }
        public string cek { get; set; }
        public string yonetim { get; set; }
        public string fiyatUpdate { get; set; }
        public string bankaBtnRaporla { get; set; }
        public string bankaBtnBankaSil { get; set; }
        public string bankaBtnEkle { get; set; }
        public string bankaBtnParaYatir { get; set; }
        public string bankaBtnParaCekmeOdeme { get; set; }
        public string bankaBtnDuzelt { get; set; }
        public string bankaBtnSil { get; set; }
        public string cariBtnYeniCari { get; set; }
        public string cariBtnCariDuzenle { get; set; }
        public string cariBtnCarisil { get; set; }
        public string cariBtnStoksuzSatis { get; set; }
        public string cariBtnStokluSatis { get; set; }
        public string cariBtnTahsilatYap { get; set; }
        public string cariBtnOdemeYap { get; set; }
        public string cariBtnAlacaklandir { get; set; }
        public string cariBtnBorclandir { get; set; }
        public string cariBtnTaksitliSatis { get; set; }
        public string cariBtnTahsilatMakbuzuKes { get; set; }
        public string cariBtnOdemeMakbuzuKes { get; set; }
        public string cariBtnDuzelt { get; set; }
        public string cariBtnSil { get; set; }
        public string cariBtnCariIslRapor { get; set; }
        public string cariBtnCariHesapEksRapor { get; set; }
        public string cariBtnCariRapor { get; set; }
        public string cekBtnAra { get; set; }
        public string cekBtnYeniVerilenCek { get; set; }
        public string cekBtnYeniAlinanCek { get; set; }
        public object cekBtnDuzelt { get; set; }
        public object cekBtnTahsilEt { get; set; }
        public object cekBtnOdemeYap { get; set; }
        public string cekBtnSil { get; set; }
        public string faturaBtnYeniSatisFaturasi { get; set; }
        public string faturaBtnYeniAlisFaturasi { get; set; }
        public string faturaBtnFaturaSil { get; set; }
        public string faturaBtnFaturaBas { get; set; }
        public string faturaBtnMakbuzBas { get; set; }
        public string faturaBtnRaporAl { get; set; }
        public string faturaBtnYeniIrsaliye { get; set; }
        public string faturaBtnIrsaliyeFaturalandir { get; set; }
        public string faturaBtnIrsaliyeYazdir { get; set; }
        public string kasaBtnGirisYap { get; set; }
        public string kasaBtnCikisYap { get; set; }
        public string kasaBtnDuzelt { get; set; }
        public string kasaBtnSil { get; set; }
        public string kasaBtnYazdir { get; set; }
        public string stokBtnYeniStok { get; set; }
        public object stokBtnStokKaydet { get; set; }
        public string stokBtnStokDuzenle { get; set; }
        public string stokBtnStoksil { get; set; }
        public string stokBtnStokGirisi { get; set; }
        public string stokBtnStokCikisi { get; set; }
        public string stokBtnDuzelt { get; set; }
        public string stokBtnSil { get; set; }
        public string stokBtnEtiketBas { get; set; }
        public string stokBtnStokHareket { get; set; }
        public string stokBtnTopluStokRapor { get; set; }
        public string taksitBtnHizliTaksitlendir { get; set; }
        public string taksitBtnTaksitDuzenle { get; set; }
        public string taksitBtnTaksitSil { get; set; }
        public string taksitBtnTaksitIslTahsilEt { get; set; }
        public string taksitBtnTaksitIslIadeEt { get; set; }
        public string subeAdi { get; set; }
        public string ajandaGorevatama { get; set; }
        public string ajandaGorevlisteleme { get; set; }
        public string stoksuzUrunEkleme { get; set; }
        public string teklifBtnTeklifSiparis { get; set; }
        public string teklifBtnYeniVerilenTeklif { get; set; }
        public string teklifBtnYeniAlinanTeklif { get; set; }
        public string teklifBtnYeniVerilenSiparis { get; set; }
        public string teklifBtnYeniAlinanSiparis { get; set; }
        public string teklifBtnDuzeltTeklifSiparis { get; set; }
        public string teklifBtnSilTeklifSiparis { get; set; }
        public string teklifBtnIptalEtTeklifSiparis { get; set; }
        public string teklifBtnRaporAl { get; set; }
        public string teklifBtnBasTeklifSiparis { get; set; }
        public string teklifBtnAlinanTeklifVerilenSipariseDonustur { get; set; }
        public string teklifBtnVerilenTeklifAlinanSipariseDonustur { get; set; }
        public string teklifBtnAlinanSiparisIrsaliyeDonustur { get; set; }
        public string teklifBtnVerilenSiparisFaturaDonustur { get; set; }
        public string efaturaBtnEfatura { get; set; }
        public string efaturaTAslaklarToolStripMenuItem { get; set; }
        public string efaturaOnayBekleyenlerToolStripMenuItem { get; set; }
        public string efaturaFaturaListesiToolStripMenuItem { get; set; }
        public string efaturaOnayBekliyorToolStripMenuItem { get; set; }
        public string efaturaOnayBekleyenlerToolStripMenuItem1 { get; set; }
        public string efaturaFaturaListesiToolStripMenuItem1 { get; set; }
        public string efaturaMuKellefliStesiToolStripMenuItem { get; set; }
        public string efaturaAYarlartoolStripMenuItem { get; set; }
        public string efaturaBtnTaslakYazdir { get; set; }
        public string efaturaBtnTaslakFaturaOlustur { get; set; }
        public string efaturaBtnTaslakFaturalandir { get; set; }
        public string efaturaBtnTaslakSil { get; set; }
        public string efaturaBtnTaslakDuzenle { get; set; }
        public string efaturaBtnTaslakRapor { get; set; }
        public string efaturaBtnTaslakPdfindir { get; set; }
        public string efaturaBtnTaslakXmlIndir { get; set; }
        public string efaturaBtnTaslakExceleAktar { get; set; }
        public string efaturaBtnGidenYazdir { get; set; }
        public string efaturaBtnGidenIptalEt { get; set; }
        public string efaturaBtnGidenEmailGonder { get; set; }
        public string efaturaBtnGidenTekrarGonder { get; set; }
        public string efaturaBtnGidenLogKayitlari { get; set; }
        public string efaturaBtnGidenRapor { get; set; }
        public string efaturaBtnGidenPdfindir { get; set; }
        public string efaturaBtnGidenXmlIndir { get; set; }
        public string efaturaBtnGidenExceleAktar { get; set; }
        public string efaturaBtnGidenFaturaDurumKontrol { get; set; }
        public string efaturaBtnGelenOkunduIsaretle { get; set; }
        public string efaturaBtnGelenYazdir { get; set; }
        public string efaturaBtnGelenOnayla { get; set; }
        public string efaturaBtnGelenReddet { get; set; }
        public string efaturaBtnGelenLogKayitlari { get; set; }
        public string efaturaBtnGelenRapor { get; set; }
        public string efaturaBtnGelenPdfindir { get; set; }
        public string efaturaBtnGelenXmlIndir { get; set; }
        public string efaturaBtnGelenExceleAktar { get; set; }
        public string ajandaBildirimGoster { get; set; }
        public string stokBtnSubedenAktar { get; set; }
        public string personelTakip { get; set; }
        public string programAyarListe { get; set; }
        public bool izleme { get; set; }
        public string gider { get; set; }
        public string giderBtnEkle { get; set; }
        public string giderBtnDuzenle { get; set; }
        public string giderBtnGelirGiderSil { get; set; }
        public string giderGrbRaporlama { get; set; }
        public string giderBtnGelirIsle { get; set; }
        public string giderBtnGiderIsle { get; set; }
        public string giderBtnOdemeTahsilat { get; set; }
        public string giderBtnDuzelt { get; set; }
        public string giderBtnSil { get; set; }
        public string kasaBtnEkle { get; set; }
        public string kasaBtnDuzenle { get; set; }
        public string kasaBtnKasaSil { get; set; }
        public string kasaBtnBankayaVirman { get; set; }
        public string kasaBtnKasadanKasayaVirman { get; set; }
        public string faturaBtnFaturaDuzelt { get; set; }
        public string stokTxtAlisFiyati { get; set; }
        public List<object> ajanda { get; set; }
        public List<object> genelayar { get; set; }
        public List<object> hizlisatisayar { get; set; }
    }
}
